### ISSUE TITLE
Highlight support on Windows

### ISSUE THREAD

**Issue by phibos** [DinoTools/pysslscan#22]
The used escape sequences to highlight the output are interpreted by *nix shells like bash and zsh. On windows the scanner just prints wired characters.

**Comment by obeleh** [comment]
I think this library would help: https://pypi.python.org/pypi/colorama/0.2.4

**Comment by phibos** [comment]
I have merged the feature into the master branch. Please feel free to have a look at the merge request #29 for more information.
